#!/usr/bin/env bash
# script hat manages manage_my_process
# When passing the argument start:
#	1. Starts manage_my_process
# 	2. Creates a file containing its PID in /var/run/my_process.pid
# 	3. Displays manage_my_process started
# When passing the argument stop:
# 	1.Stops manage_my_process
# 	2. Deletes the file /var/run/my_process.pid
# 	3.Displays manage_my_process stopped
# When passing the argument restart
# 	1. Stops manage_my_process
# 	2. Deletes the file /var/run/my_process.pid
# 	3. Starts manage_my_process
# 	4. Creates a file containing its PID in /var/run/my_process.pid
# 	5. Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart}
# 	if any other argument or no argument is passed

arg=$1
file="/var/run/my_process.pid"

start_n_createfile()
{
	./manage_my_process &
	echo "$!" > "$file"
}

kill_n_rmfile()
{
	sudo pkill -f "./manage_my_process"
	rm "$file"
}

if [ "$arg" == "start" ]
then
	echo "manage_my_process started"
	start_n_createfile
elif [ "$arg" == "stop" ]
then
	echo "manage_my_process stopped"
	kill_n_rmfile
elif [ "$arg" == "restart" ]
then
	echo "manage_my_process restarted"
	kill_n_rmfile
	start_n_createfile
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
