#!/usr/bin/env bash
# Script displays:
# "To infinity and beyond"
# "I am invincible!!!" when receiving a SIGTERM signal

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
