#!/usr/bin/env bash
# Script dispalys numbers from 1 to 100:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Dispalys Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

n=1
while [ $n -le 100 ]
do
	if (( n % 3 == 0 )) && (( n % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( n % 3 == 0 ))
	then
		echo "Fizz"
	elif (( n % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	((n++))
done
