#!/usr/bin/env bash
# This script displays the content of the file "/etc/passwd":
# displays username, user id and home diredtory path for the user

fname="/etc/passwd"
while read line
do
	echo "${line}" | cut -d ':' -f1,3,6
done < "${fname}"
