#!/usr/bin/env bash
# Script displays the time for 0-12, minutes from 1- 59

h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	((h++))

	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
done
